#!/bin/bash


export FLASK_APP=app
export FLASK_ENV=development
source backend/venv/bin/activate
cd backend

# Command dictionnary
declare -A commands
commands['run']="flask run"
commands['shell']="flask shell"
commands['init-db']="flask init-db"
commands['test']="python -m unittest"


if [ -v commands[$1] ]; 
then
    ${commands[$1]}
else
    echo "run:     run server"
    echo "shell:   run shell"
    echo "init-db:   init-db"
    echo "test:   run tests"
fi


